### ISSUE TITLE
Use Passport.js instead of next-auth

### ISSUE THREAD

**Issue by r29taheri** [Inflow-Music-Co/inflow-app#136]
Currently we are using next-auth for authentication with Twitter, we should check Passport.js implementation and use that instead of next-auth.

[Passport.js doc for implementing Login with Twitter](https://www.passportjs.org/docs/twitter/)

**Comment by rvmelkonian** [comment]
need to test next-auth again to see how it's holding up currently

**Comment by rvmelkonian** [comment]
closing this stale issue
