### ISSUE TITLE
Inflow Radio UI 

### ISSUE THREAD

**Issue by rvmelkonian** [Inflow-Music-Co/inflow-app#170]
We've had several discussions around the concept of a public inflow radio. A mix of songs from artist profiles. We need to update the designs for this radio feel. After this we can work on this feature. 

Some notes from the call. 

**Mobile**
- [x] Change player to be titled 'InFlow Radio' 

**Additional Things to confirm if still need doing**
- [ ] Make player skinnier
- [ ] Make it sticky
- [ ] Bring back filters but tidy
- [ ] Put radio to the bottom

**Comment by rvmelkonian** [comment]
Reminder @LukeAnnison to maybe update the tasks on this issue

**Comment by LukeAnnison** [comment]
Have updated radio to be able to bring in public songs of artists on current page. If you click anywhere on the track component (list) it plays.

Now just need to confirm if the additional points above still need to be done.

**Comment by rvmelkonian** [comment]
old points are irrelevant now, closing this issue

**Comment by rvmelkonian** [comment]
I'm still getting buggy behaviour on this, in some occasions. I haven't looked into what is causing the issue. Sometimes on click the track does not play. @r29taheri @LukeAnnison , are you able to reproduce this bug? The code is merged to dev.

**Comment by LukeAnnison** [comment]
Seems it's working fine for me and Rez. Are you checking this on dev or on the live link? 

**Additional tasks for this**

- [ ]  Add return icon to play state after it is paused on the bottom controls
- [ ] Change image on bottom controls to update with song
- [ ] Confirm and Fix Richard's play issue above
- [ ] Add in skip tracks feature
