### ISSUE TITLE
Mobile navigation background not appearing

### ISSUE THREAD

**Issue by LukeAnnison** [Inflow-Music-Co/inflow-app#194]
On mobile on the live link the nav menu background behind the burger icon and home icon doesn't appear. 

![image](https://user-images.githubusercontent.com/8157151/152401337-b90490d4-7657-46f1-9ee8-a011ba9649ea.png)

It should look like this 
![image](https://user-images.githubusercontent.com/8157151/152401271-2e523281-6621-4acc-bbea-927ab8277fe8.png)

**Comment by LukeAnnison** [comment]
This seems to be resolved by changing the image to a different background image. Please someone else check if it is there on mobile to confirm it can be closed.

**Comment by rvmelkonian** [comment]
thanks @LukeAnnison, have checked this and working.
